### ISSUE TITLE
소스코드 개선 

### ISSUE THREAD

**Issue by hmkim01** [kimhyun5u/jbnu-newtab#31]
매일을 보냈는데 수신이안와서 여기에도 올립니다.
[jbnu-newtab-main.zip](https://github.com/jbnu-plus/jbnu-newtab/files/12208524/jbnu-newtab-main.zip)
수정사항
글꼴 > IBM Sans로 교체
전북대학교 로고 현재 로고로 최신화
전북대학교 로고 가 창크기에 맞게 이동
백그라운드 배경을 건지광장으로 교체
백그라운드 배경이 창크기에 따라 2개를 표시되는것을 수정
키워드 검색 색을 현재 전북대학교의 대표색상에 맞춰서 변경
키워드 크기를 줄이려다가 실패
전북대학교 서버시간을 가져올려다가 실패 (소스코드는 안에 남아있음)
<img width="1280" alt="스크린샷 2023-07-30 143721" src="https://github.com/jbnu-plus/jbnu-newtab/assets/140933008/de598477-497c-4613-911d-1189f7bd04db">

**Comment by kimhyun5u** [comment]
안녕하세요! 프로젝트에 관심 가져주셔서 감사합니다. 해당 수정사항 PR로 주실 수 있을까요 ? 코드 확인 후 머지 해드리겠습니다!

**Comment by hmkim01** [comment]
뭘 하긴했는데 제대로 된지 잘모르겠습니다... 깃허브는 처음 수정해 보는지라 😵😵😵

**Comment by kimhyun5u** [comment]
그러면 코드 확인해보고 반영하겠습니다 :)
